### ISSUE TITLE
Key-reuse check algorithm re-adds keys for each sector

### ISSUE THREAD

**Issue by aczid** [vk496/mfoc#13]
The code to check new keys adds any working keys to the list of keys to try, even if they are already in the list.
The problem is the code adds to the known keys buffer for each sector that has a valid key, so it will just keep adding more copies for the same key used in multiple sectors, leading to an explosion of candidate keys to try.
https://github.com/vk496/mfoc/blob/hardnested/src/mfoc.c#L371

Leading to output like this:
```
[Key: 000000000000] -> [xxxxxxxxxxxxxxxxxxxxxx/................x]
[Key: 000000000000] -> [xxxxxxxxxxxxxxxxxxxxxx/................x]
[Key: 000000000000] -> [xxxxxxxxxxxxxxxxxxxxxx/................x]
[Key: 000000000000] -> [xxxxxxxxxxxxxxxxxxxxxx/................x]
[Key: 000000000000] -> [xxxxxxxxxxxxxxxxxxxxxx/................x]
[Key: 000000000000] -> [xxxxxxxxxxxxxxxxxxxxxx/................x]
[Key: 000000000000] -> [xxxxxxxxxxxxxxxxxxxxxx/................x]
[Key: 000000000000] -> [xxxxxxxxxxxxxxxxxxxxxx/................x]
```

In my experience the code then actually hangs at some point, I didn't exactly narrow down why yet.

**Comment by aczid** [comment]
To work around this I just comment the goto statement here https://github.com/vk496/mfoc/blob/hardnested/src/mfoc.c#L597 and then everything works normally.

**Comment by earthnuker** [comment]
Hi,

i guess i added the check for existing keys and forgot to commit it, whoops, PR #14 should fix this

best regards,

Earthnuker

**Comment by aczid** [comment]
Can confirm this PR resolves the issue. Thank you!

**Comment by aczid** [comment]
Don't you think it would be smarter and just as complete to only test the last found key rather than all of the known keys again?

**Comment by aczid** [comment]
I tried to run this fixed version from your PR last night, but the tool actually got stuck in a loop, cracking the same key over and over again.

**Comment by aczid** [comment]
I tried the latest master and it seems this issue is resolved now.
The remaining (minor) issue I still see is that the key reuse algorithm rechecks every recovered key on every sector in between each attempt to crack a new sector key. But at least it's stable and and otherwise correct now. Thank you!

**Comment by vk496** [comment]
Hi,

The project moved to https://github.com/nfc-tools/mfoc-hardnested

If you feel that this problem should still be solved, reopen the issue there please. Thank you :)
