### ISSUE TITLE
Problem for install "configure.ac:19 error"

### ISSUE THREAD

**Issue by Benilm** [vk496/mfoc#3]
Hi, i have a problem during installation after git clone.
when i do the command autoreconf -is i have a fail message...
in attachment the full lines.
![IMG_7770](https://user-images.githubusercontent.com/50166692/57010904-64979900-6bff-11e9-9616-4de4b84157c6.jpg)

**Comment by Benilm** [comment]
![Capture d’écran 2019-05-01 à 10 58 22](https://user-images.githubusercontent.com/50166692/57011077-28186d00-6c00-11e9-91c0-6a80928cca52.png)

**Comment by Benilm** [comment]
i Find solution but now my problem is issues#2 .... and i have already install with git clone -b hardenested linkGIT

**Comment by vk496** [comment]
Duplicate of #2
